# Generated by Django 4.2.3 on 2023-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_environment', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('network', 'Network'), ('hacking', 'Hacking'), ('cyber_security', 'Cyber Security'), ('threat_modeling', 'Threat Modeling')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
