# Generated by Django 4.2.3 on 2023-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_environment', '0003_product_category_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('', 'All'), ('network', 'Network'), ('hacking', 'Hacking'), ('cyber_security', 'Cyber Security'), ('threat_modeling', 'Threat Modeling')], default='', max_length=20),
        ),
    ]
