# Generated by Django 4.2.3 on 2023-07-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_environment', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('', 'All'), ('network', 'Network'), ('hacking', 'Hacking'), ('cyber_security', 'Cyber Security'), ('threat_modeling', 'Threat Modeling')], default='all', max_length=20),
        ),
    ]
