# Generated by Django 4.2.3 on 2023-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_environment', '0007_loginuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
