# Generated by Django 4.2.3 on 2023-07-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_environment', '0008_loginpassword_delete_loginuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
