# Generated by Django 4.2.3 on 2023-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_environment', '0009_fakeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeuser',
            name='job_title',
            field=models.CharField(default='Unknown', max_length=75),
        ),
    ]
